codecov:
  branch: master
  bot: skyzyx

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1.25
        branches:
          - master
          - feature/*

    patch:
      default:
        target: auto
        branches:
          - master
          - feature/*

    changes:
      default:
        branches:
          - master
          - feature/*

  ignore:
    - config/.*
    - gradle/.*
    - test/.*
    - .*/vendor/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
  branches:
    - master
    - feature/*
